### ISSUE TITLE
Serve a InputStream

### ISSUE THREAD

**Issue by bollerdominik** [Backblaze/b2-sdk-java#65]
I am trying to migrate from S3 to B2

Following is my spring boot code which serves a video file

		@GetMapping(value = "/files/{user}/{filename}")
		public ResponseEntity<Resource> getImageAsResponseEntity(@PathVariable String filename, @PathVariable String user) throws IOException {

			HttpHeaders headers = getHttpHeaders(filename);

			S3ObjectInputStream s3ObjectInputStream = s3Service.get(user + "/" + filename);
			InputStreamResource resource = new InputStreamResource(s3ObjectInputStream);

			return new ResponseEntity<>(resource, headers, HttpStatus.OK);
		}

How can I achieve the same with B2? I only see methods to download the whole file to memory and then serve it which is not what I want

**Comment by certainmagic** [comment]
Hi Dominik --

It sounds like your goal is to get access to the InputStream from the response.  The download methods on B2StorageClient all take a B2ContentSink argument.  As you saw, the sdk includes two implementations of that -- B2ContentMemory and B2ContentFileWriter, for writing to memory and a file respectively.  You can make your own implementation of B2ContentSink and override readContent() which is given the headers and the InputStream from the server's response.  Does that answer your question?

ttfn,
ab

ps. If you don't need to proxy the stream through your server, you might consider creating a url with a time restriction and giving that to your client so it can download the file directly from B2 instead of proxying it through your server.  See b2_get_download_authorization [1] and B2StorageClient.getDownloadAuthorization().


[1] https://www.backblaze.com/b2/docs/b2_get_download_authorization.html

**Comment by bollerdominik** [comment]
Thanks for the quick reply.

I created  simple B2InputStreamSink which implements B2ContentSink and stores the input stream. However the moment my application responds with return `new ResponseEntity<>(resource, getHttpHeaders(), HttpStatus.OK);` it throws a SocketException

		java.net.SocketException: Socket is closed
			at sun.security.ssl.SSLSocketImpl.checkEOF(SSLSocketImpl.java:1542) ~[na:1.8.0_144]
			at sun.security.ssl.AppInputStream.read(AppInputStream.java:95) ~[na:1.8.0_144]
			at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.11.jar:4.4.11]
			at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197) ~[httpcore-4.4.11.jar:4.4.11]
			at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176) ~[httpcore-4.4.11.jar:4.4.11]
			at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135) ~[httpclient-4.5.7.jar:4.5.7]
			at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:148) ~[httpclient-4.5.7.jar:4.5.7]
			at org.springframework.util.StreamUtils.copy(StreamUtils.java:142) ~[spring-core-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:132) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:124) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.http.converter.ResourceHttpMessageConverter.writeInternal(ResourceHttpMessageConverter.java:45) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:293) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:223) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
			at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) ~[tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
			at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.16.jar:9.0.16]
			at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]

**Comment by certainmagic** [comment]
Got it.  Thanks for the polite way of saying "no, that doesn't answer my
question".  :)

I think the mismatch is that the SDK cleans up the response as soon as you
return from readInput() --- since it's expecting you to be done reading the
input and it wants to clean up the response and get the http connection
returned to the pool.  We don't currently support holding on to the input
stream after you've returned.  I don't yet have a clean idea about how to
implement that in a way that the resources definitely get cleaned up.  Do
you?

On a related note, have you considered having clients download the content
directly from B2 so you don't need to proxy it?

ttfn,
ab

**Comment by bollerdominik** [comment]
;)

Yes I thought about getting direct links to B2. It seems like that is our only option but this path requires a bigger change on the current application and will make our migration more complicated.

**Comment by certainmagic** [comment]
I'm not familiar with Spring and you're probably way ahead of me on
thinking about this, but I'll ask anyway.  Can the response body you return
from this code just be a redirect with the url to the stream?  Maybe
there's something special in your headers that would be lost with that
approach...?

ttfn,
ab

**Comment by certainmagic** [comment]
Hi Dominik --

How is it going? I'm wondering I've been making this more complicated than it needs to be.  

B2StorageClient has methods like getDownloadUrlByName() which returns a URL you can use to download the file.  If the file is in a private bucket, you can use info returned by getDownloadAuthorization() to make a URL you can use without involving the SDK.  It seems like you can probably use some other HTTP api to make a stream for the contents of that file and use that in your code.

Does this make sense?

ttfn,
ab

**Comment by certainmagic** [comment]
Hi Dominik --

Since I haven't heard from you in almost 6 weeks, I'm going to close this issue.  If you'd like to continue the conversation, please reopen this or open a new issue whenever you're interested.

thanks,
ab

**Comment by bollerdominik** [comment]
Another month - another expensive AWS bill and I am still interested in moving to B2.
I tried your suggestion of getting a download link to the file and streaming it but I couldn't find a way to stream it without downloading the file to memory first.

I tried making http calls with Springs `RestTemplate` and standard Java IO `new URL(url).openStream()` but it all seems to download the full file to memory first before serving it.

Reopening with the hope to find a way to implement this `S3ObjectInputStream` behavior in to B2

**Comment by certainmagic** [comment]
Hi Dominik --

I'm still not a Spring user much less an expert.  :(

Googling around, I see that there's something in Spring boot called a StreamingResponseBodyController.  That looks promising.  You can
probably return one of those with an input stream you get from a URL.

In [this article](https://www.oodlestechnologies.com/blogs/How-To-Download-A-File-Directly-From-URL-In-Spring-Boot/), the author shows how to stream the contents of a local file as a StreamingResponseBody.  After getting the download url (and authToken if needed) from the SDK, I suspect you can do something similar using java's URL and URLConnection classes instead of FileInputStream:

        final URL url = new URL(urlString);
        final URLConnection urlCxn = url.openConnection();

       ...
       final OutputStream outs = urlCxn.getOutputStream();

ttfn,
ab
